# Generated by Django 2.0.2 on 2018-03-17 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizItem',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='quiz_item',
            new_name='question',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question')},
        ),
    ]
